### ISSUE TITLE
"Never make any assumptions about the presence of data"

### ISSUE THREAD

**Issue by meisterluk** [mlbright/darksky#13]
I recommend adding "omitempty" to all struct field tag values. Why? Because the [documentation](https://developer.forecast.io/docs/v2#response-headers) specifies:

> Never make any assumptions about the presence of data or lengths of arrays. For example, a lack of data in our data sources may cause data to be missing, and Daylight Savings Time may cause a day to consist of 23 or 25 hours (instead of the usual 24). Always check for the presence of data before trying to use it.

**Comment by mlbright** [comment]
I'm not sure how this impacts the users of this library (here my lack of Golang skills is showing.) Could you explain this in a pull request to the new [DarkSky](https://github.com/mlbright/darksky) repo? This repo is officially deprecated, see #14.

**Comment by mlbright** [comment]
Hold your horses. This repo is NOT deprecated, so you can create your PR here. (Who knew you could rename GitHub repos?)
