### ISSUE TITLE
nearestStormDistance should be float64

### ISSUE THREAD

**Issue by ironwallaby** [mlbright/darksky#28]
Hello! I'm one of the developers of the Dark Sky API. We were interacting with a client and there was some confusion over the proper typing of some of the return values from our API!

In particular, the return value of `nearestStormDistance` should be a `float64`: while we currently only return integer values for this property, we make no guarantee that this will always be the case, and so clients should treat this property as if may have a fractional component.

https://github.com/mlbright/darksky/blob/master/v2/forecast.go#L51

I did a quick double-check and all of the other properties appear to have correct typing rules. (Everything is a `float64`, except for times (which are integers) and `precipType` (which is a string).)

**Comment by mlbright** [comment]
See #29
